
//package org.soaphandler.inserver.ws.service;
package org.soaphandler.inserver.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://service.ws.inserver.SoapHandler.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerName", targetNamespace = "http://service.ws.inserver.SoapHandler.org/", className = "org.soaphandler.inserver.ws.service.GetServerName")
    @ResponseWrapper(localName = "getServerNameResponse", targetNamespace = "http://service.ws.inserver.SoapHandler.org/", className = "org.soaphandler.inserver.ws.service.GetServerNameResponse")
    public String getServerName();

}
