
package com.globinch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyJaxWSHello", targetNamespace = "http://globinch.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyJaxWSHello {


    /**
     * 
     * @param name
     * @return
     *     returns com.globinch.JxRes
     */
    @WebMethod
    @WebResult(name = "JXWsRes", partName = "JXWsRes")
    public JxRes getJXWsRes(
        @WebParam(name = "name", partName = "name")
        String name);

}
