
package com.globinch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyJaxWSHelloService", targetNamespace = "http://globinch.com", wsdlLocation = "http://127.0.0.1:8088/MyJaxWSService?wsdl")
public class MyJaxWSHelloService
    extends Service
{

    private final static URL MYJAXWSHELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYJAXWSHELLOSERVICE_EXCEPTION;
    private final static QName MYJAXWSHELLOSERVICE_QNAME = new QName("http://globinch.com", "MyJaxWSHelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8088/MyJaxWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYJAXWSHELLOSERVICE_WSDL_LOCATION = url;
        MYJAXWSHELLOSERVICE_EXCEPTION = e;
    }

    public MyJaxWSHelloService() {
        super(__getWsdlLocation(), MYJAXWSHELLOSERVICE_QNAME);
    }

    public MyJaxWSHelloService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYJAXWSHELLOSERVICE_QNAME, features);
    }

    public MyJaxWSHelloService(URL wsdlLocation) {
        super(wsdlLocation, MYJAXWSHELLOSERVICE_QNAME);
    }

    public MyJaxWSHelloService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYJAXWSHELLOSERVICE_QNAME, features);
    }

    public MyJaxWSHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyJaxWSHelloService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyJaxWSHello
     */
    @WebEndpoint(name = "MyJaxWSSEIPort")
    public MyJaxWSHello getMyJaxWSSEIPort() {
        return super.getPort(new QName("http://globinch.com", "MyJaxWSSEIPort"), MyJaxWSHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyJaxWSHello
     */
    @WebEndpoint(name = "MyJaxWSSEIPort")
    public MyJaxWSHello getMyJaxWSSEIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://globinch.com", "MyJaxWSSEIPort"), MyJaxWSHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYJAXWSHELLOSERVICE_EXCEPTION!= null) {
            throw MYJAXWSHELLOSERVICE_EXCEPTION;
        }
        return MYJAXWSHELLOSERVICE_WSDL_LOCATION;
    }

}
